# Generated by Django 4.2.4 on 2023-09-01 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Number of days the campaign will run')),
                ('targeted_amount', models.DecimalField(decimal_places=2, help_text='Targeted fundraising amount', max_digits=10)),
                ('document_proof', models.FileField(help_text='Document proof for the campaign', upload_to='campaigns/')),
                ('description', models.TextField(help_text='Description of the fundraising campaign')),
                ('hospital_account_details', models.TextField(help_text='Hospital account details for donations')),
                ('creator', models.ForeignKey(help_text='User who created the campaign', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
